# Data Cleaning & Preprocessing

Prepare the dataset for sentiment analysis by:
- Cleaning text data
- Handling missing values
- Standardizing variables
- Creating a clean dataset for modeling

This notebook focuses on preparing both text and structured features.

In [1]:
#Import Libraries

import pandas as pd
import numpy as np
import re
import nltk
from nltk.corpus import stopwords

In [2]:
#Download stopwords
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/olgabencomo/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [3]:
#Load the dataset

df = pd.read_csv('/Users/olgabencomo/Desktop/Proyectos Portafolio/Sentiment Analysis Project/data/raw/Womens Clothing E-Commerce Reviews.csv')
df.head()

,Unnamed: 0,Clothing ID,Age,Title,Review Text,Rating,Recommended IND,Positive Feedback Count,Division Name,Department Name,Class Name
0,0,767,33,NaN,Absolutely wonderful - silky and sexy and comf...,4,1,0,Initmates,Intimate,Intimates
1,1,1080,34,NaN,Love this dress! it's sooo pretty. i happene...,5,1,4,General,Dresses,Dresses
2,2,1077,60,Some major design flaws,I had such high hopes for this dress and reall...,3,0,0,General,Dresses,Dresses
3,3,1049,50,My favorite buy!,"I love, love, love this jumpsuit. it's fun, fl...",5,1,0,General Petite,Bottoms,Pants
4,4,847,47,Flattering shirt,This shirt is very flattering to all due to th...,5,1,6,General,Tops,Blouses

In [4]:
#Initial exploration of the dataset

df.info()


df.isnull().sum()

<class 'pandas.DataFrame'>
RangeIndex: 23486 entries, 0 to 23485
Data columns (total 11 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Unnamed: 0               23486 non-null  int64
 1   Clothing ID              23486 non-null  int64
 2   Age                      23486 non-null  int64
 3   Title                    19676 non-null  str
 4   Review Text              22641 non-null  str
 5   Rating                   23486 non-null  int64
 6   Recommended IND          23486 non-null  int64
 7   Positive Feedback Count  23486 non-null  int64
 8   Division Name            23472 non-null  str
 9   Department Name          23472 non-null  str
 10  Class Name               23472 non-null  str
dtypes: int64(6), str(5)
memory usage: 2.0 MB

Unnamed: 0                    0
Clothing ID                   0
Age                           0
Title                      3810
Review Text                 845
Rating                        0
Recommended IND               0
Positive Feedback Count       0
Division Name                14
Department Name              14
Class Name                   14
dtype: int64

 Observations
- Identify missing values
- Check data types
- Understand key variables

In [5]:
df = df[['Review Text', 'Rating']].dropna()

In [6]:
#Text cleaning function

stop_words = set(stopwords.words('english'))

def clean_text(text):
    text = str(text).lower()
    text = re.sub(r"http\S+|www\S+|https\S+", '', text)
    text = re.sub(r"[^a-zA-Z\s]", '', text)
    text = re.sub(r"\s+", ' ', text).strip()
    
    # remove stopwords
    text = " ".join([word for word in text.split() if word not in stop_words])
    
    return text

In [7]:
df['Clean_Review'] = df['Review Text'].apply(clean_text)

In [8]:
df[['Review Text', 'Clean_Review']].head()

,Review Text,Clean_Review
0,Absolutely wonderful - silky and sexy and comf...,absolutely wonderful silky sexy comfortable
1,Love this dress! it's sooo pretty. i happene...,love dress sooo pretty happened find store im ...
2,I had such high hopes for this dress and reall...,high hopes dress really wanted work initially ...
3,"I love, love, love this jumpsuit. it's fun, fl...",love love love jumpsuit fun flirty fabulous ev...
4,This shirt is very flattering to all due to th...,shirt flattering due adjustable front tie perf...

In [9]:
# Create target variable
def sentiment_label(rating):
    if rating >= 4:
        return "Positive"
    elif rating <= 2:
        return "Negative"
    else:
        return "Neutral"

df['sentiment'] = df['Rating'].apply(sentiment_label)

In [10]:
df['sentiment'].value_counts()

sentiment
Positive    17448
Neutral      2823
Negative     2370
Name: count, dtype: int64

In [12]:
#Save cleaned dataset 

df.to_csv('/Users/olgabencomo/Desktop/Proyectos Portafolio/Sentiment Analysis Project/data/processed/data_with_sentiment.csv', index=False)